<p>Hi $teacherName$</p>
<p>You currently have no lessons booked for the coming week. Better luck next week! If you're not doing so yet, try the following:</p>
<ol>
 <li>Mark your availability within the "hot" time slots (Mon-Sun 6-9PM, Sat-Sun 9-11AM Beijing time).</li>
 <li>Spread out your availability over several days (e.g. 2 hours on Monday, 2 hours on Wednesday, 2 hours on Friday, 2 hours on Sunday).</li>
 <li>Mark your schedule on a Sunday (parents have access to teachers' schedules starting from Monday).</li>
</ol>
<p>Once you've done the above, it will be an easy task for us to promote you on our social media pages.</p>
<p>Hope to see you soon in the classroom,</p>
<p>VIPKID</P>