<p>Dear $teacherName$:</p>
<br>
<p>This is a reminder about your upcoming interview + demo class at $scheduledDateTime$ on  <span style="font-size: 1.0em">YOUR LOCAL TIME</span>. Please note that you are free to reschedule within 48 hours,  but cancellation and rescheduling within 24 hours is not allowed.
</p>

Note:
 Please make sure to watch the following videos before your interview + demo class. These initial training videos will demonstrate the techniques and methodology we require of our teachers.
<br>
Feel free to contact us at teachvip@vipkid.com.cn if you have any questions.You can also reach us on Skype. Our Skype name is Teach VIPKID.

<p>
<div  style="font-style: italic;">
---------------------------------------------------------------------------------
<br>
<strong>Tutorials Section 3:</strong>
<br>
-To know how to enter classroom:  <a href="https://www.youtube.com/watch?v=1M31jI5gxR4"> Enter Classroom</a>
<br>
-To watch a demonstration of a demo lesson: <a href="https://youtu.be/it5fb0KlUjU">https://youtu.be/it5fb0KlUjU</a>
<br>
-To learn about tips of teaching foundational level ESL learners: <a href="https://youtu.be/BOBEPG_anBA this"> https://youtu.be/BOBEPG_anBA this</a>
<br>
---------------------------------------------------------------------------------
</div>

<p>Best Regards.<br>The VIPKID Recruiting Team</p>