<p>Dear $teacherName$,</p>

<p>You have 2 days left to send us all required documents. Please note that without required information, we cannot proceed with your application and send you to teacher training.</p>

<p>Feel free to contact us at <a href="mailto:teachvip@vipkid.com.cn">teachvip@vipkid.com.cn</a> if you have any questions.</p>

<p>
<br>
<p> Best Regards,<br>The VIPKID Recruiting Team</p>
