<p>Dear $teacherName$,</p>

<p>Thank you for applying for VIPKID Teacher. We appreciate your interest in our positions.</p>

<p>We received more than 200 applications for the position, and the hiring process has been a very competitive one. Although we were impressed with your qualifications, we have decided not to move your application forward. 
However, we greatly appreciate your interest in working with us and wish you the best of luck with your job search.</p>
<p>
<p> Best Regards,<br>The VIPKID Recruiting Team</p>