<p>Dear $teacherName$, </p>

<p>We are impressed by your resume and would like to invite you for a <span style="text-decoration: underline;">30</span> minutes interview + demo class. To schedule your interview and demo class, please log into your account at <a href="http://teacher-recruitment.vipkid.com.cn/apply?recruitmentId=$recruitmentId$">teacher-recruitment.vipkid.com.cn</a>. You will also find all information regarding the demo class in your account.</p>
<p>
Feel free to contact us at <a href="mailto:teachvip@vipkid.com.cn">teachvip@vipkid.com.cn</a> if you have any questions.You can also reach us on Skype. Our Skype name is Teach VIPKID.
</p>

<div  style="font-style: italic;">
---------------------------------------------------------------------------------
<br>
<strong>Tutorials Section 2:</strong>
<br>
- To schedule an interview and demo class:  <a href="https://www.youtube.com/watch?v=lI2Xdv7VjsA"> Schedule an Interview</a>
<br>
-To know our expectations for teachers:  <a href="http://resource.vipkid.com.cn/teacher_recruitment/Demo%20Class%20Training%20Video%20List%20.docx"> Download</a>
<br>
-For the demo class our VIPKID staff will mimic the Foundation Level student in our program so please check this video to know how to teach foundation level students:  <a href="https://youtu.be/BOBEPG_anBA">Teach foundation level students</a>

<br>
---------------------------------------------------------------------------------
</div>
<p>
<p>Best Regards,<br>The VIPKID Recruiting Team</p>