<p>Dear $teacherName$,</p>

<p>
We hope this email finds you well. Based on your practicum evaluator’s feedback of your performance, we would like to schedule a second practicum with you. This practicum is to give you an opportunity to implement the feedback given you during your first practicum. 
Please be aware that this is your final practicum opportunity. The reason why we have this procedure is to make sure that our teachers are fully prepared to teach our students.
</p>

<p><strong>
The second practicum is different from the first practicum. Please review the second practicum materials to prepare. 
</strong></p>
<p>
Our practicums are scheduled <strong>Monday-Sunday from 9am-12pm Beijing time. 
</strong>. 
</p>

<p><storng>Please click the link below to schedule your second practicum</strong>.</p>
<p><a href="http://teacher-recruitment.vipkid.com.cn/apply?recruitmentId=$recruitmentId$">teacher-recruitment.vipkid.com.cn</a>
</p>

<p><strong>
If you haven’t already, please review the New Teacher FAQs video: <a href="https://youtu.be/hK5Y5IUocMM">  review </a>
</strong></p>

<p>
<br>
<p>Best Regards,</p>
<p>VIPKID Education</p>