<p>Dear $teacherName$,</p>

<p>We hope this email finds you well. We appreciate your effort and the time you’ve put into training with us so far. Based on your practicum evaluators’ feedback of your performances, you have not successfully passed our training.</p>

<p>The training and practicum stage serves as a conditional employment offer, based on successful completion. The reason why we have this procedure is to make sure that our teachers are fully prepared to teach our students.  This email serves as a cancellation of your contract with VIPKID.</p>

<p>Thank you for your interest in working with us, and we wish you the very best in all your future endeavors.</p>

<p>
<br>

<p>Best Regards,</p>
<p>VIPKID Education</p>



 

 
