<p>Dear $teacherName$, </p>

<p><br>This email is to confirm that we have received your application. You will hear from us within a few days. </p>

<p>Your account information is as below:
<br>
<strong>Username:$loginName$</strong>
</p>

<p>Thank you again for your interest in VIPKID.</p>
<br>

<div  style="font-style: italic;">
---------------------------------------------------------------------------------
<br>
<strong>Tutorials Section 1:</strong>
<br>
- To hear the message from VIPKID CEO Cindy: <a href="https://www.youtube.com/watch?v=N2N-U35wfR8">  Thank you, VIPKID teachers!</a>
<br>
-To know if you are a good fit for VIPKID: <a href="https://www.youtube.com/watch?v=_W38BgmaJDQ"> Are you a good fit for VIPKID?</a>
<br>
---------------------------------------------------------------------------------
</div>

<p>
<p>Regards,<br>The VIPKID Recruiting Team</p>