<p>Dear $teacherName$,</p>

<p>Thank you for reviewing the VIPKID Teacher Training materials. Please proceed to booking your practicum by clicking the below link.</p>

<p><a href="http://teacher-recruitment.vipkid.com.cn/apply?recruitmentId=$recruitmentId$">teacher-recruitment.vipkid.com.cn</a></p>

<p><strong>Please review the New Teacher FAQs video as well:<a href="https://youtu.be/hK5Y5IUocMM">View</a> </strong> </p>
<p>
<br>
<p>Best regards,<br>VIPKID Education</p>
