<p>Dear $teacherName$,</p>

<p>Welcome to VIPKID!</p>
<p>Our interviewer found you to be a great addition to VIPKID and we would love to have you as a teacher with us. Please find your contract and demo class rubric below.
</p>
<ul>
<li>
Your Interview and Demo Class score: $totalScore$ </li>
<li>
Your Base Pay: $basePay$ dollars/lesson
</li>
<li>
Your contract: <a href="$contractUrl$">Download</a>
</li>
</ul>

<p>
As soon as you see this email, please log into your account on our recruitment portal and click on "next" on your page to accept your job offer, otherwise, the job offer EXPIRES IN 24 HOURS FROM YOUR INTERVIEW TIME. After you accept the job offer from us, you will have THREE DAYS to finish the "Sign Contract" step. If you do not, your account will be locked and your job offer expires with it. So if you cannot complete the "Sign Contract" step due to some extreme situations, please email us right away, so we can try to work around it.
<br>
There are three important things in your confirmation email: your contract in a PDF file, your demo rubric, and a video tutorial.
<br>
1. Please download your contract, print it, sign and date on the 5th page, initial on every page, and then scan it as a complete file into the computer. Or you can sign it digitally. 
2. The rubric is to tell you what you did well and what you still need to improve on during the demo lesson.
3. The video tutorial is to walk you through the entire "Sign Contract" step.
4. If you experience any problems uploading your files or filling out the information, please complete everything you can on the page, click on "save" and email everything you are unable to finish to us, and we can finish it for you from our end.
5. If you are able to successful complete the "Sign Contract" page on your own, then make sure to click on "submit", and we will review the info ASAP.
6. If you have any additional questions or concerns, feel free to email us!
</p>




<br>

<div  style="font-style: italic;">
---------------------------------------------------------------------------------
<br>
<strong>Tutorials Section 4:</strong>
<br>
- To know how to upload documents on the next step:  <a href="https://www.youtube.com/watch?v=FKGvOCRGrDs">  Upload documents </a>
<br>
---------------------------------------------------------------------------------
</div>
<p>
<br>
<table style= '' border-collapse: collapse;'  border='1'>
<thead>
 <tr style="text-align: center;"><td>Pass/Fail section</td><td>Pass/Fail</td></tr>
</thead>
<tbody>
<tr><td style='padding:6px; min-width:100px;  height: 25px;'>Native and Neutral North American Accent</td><td>Pass</td></tr>
<tr><td style='padding:6px; min-width:100px;  height: 25px;'>Working knowledge of phonics</td><td>Pass</td></tr>
<tr><td style='padding:6px; min-width:100px;  height: 25px;'>Positive Attitude (pleasant, humble, respectful)</td><td>Pass</td></tr>
<tr><td style='padding:6px; min-width:100px;  height: 25px;'>Engaged vs. Bored</td><td>Pass</td></tr>
<tr><td style='padding:6px; min-width:100px;  height: 25px;'>Appearance(professional attire, plain & bright background)</td><td>Pass</td></tr>
</tbody>
</table>
<br>
<p>
$resultTable$
<p>
<p>Feel free to contact us at <a href="mailto:teachvip@vipkid.com.cn">teachvip@vipkid.com.cn</a> &nbsp;if you have any questions.</p>

<p>
<br>
<p>Best Regards,<br>The VIPKID Recruiting Team</p>